version: '3'

services:

  zookeeper:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    volumes:
      - db_zookeeper:/var/zookeeper
    command: [
      "sh", "-c",
      "bin/zookeeper-server-start.sh config/zookeeper.properties"
    ]
    ports:
      - "2181:2181"
    environment:
      LOG_DIR: /tmp/logs

  kafka:
    image: strimzi/kafka:0.11.3-kafka-2.1.0
    volumes:
      - db_kafka:/var/kafka
    command: [
      "sh", "-c",
      "bin/kafka-server-start.sh config/server.properties --override listeners=$${KAFKA_LISTENERS} --override advertised.listeners=$${KAFKA_ADVERTISED_LISTENERS} --override zookeeper.connect=$${KAFKA_ZOOKEEPER_CONNECT}"
    ]
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      LOG_DIR: "/tmp/logs"
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://10.245.3.33:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: 10.245.3.33
      KAFKA_JMX_OPTS: "-Dcom.sun.management.jmxremote=true -Dcom.sun.management.jmxremote.authenticate=false -Dcom.sun.management.jmxremote.ssl=false -Djava.rmi.server.hostname=10.245.3.33 -Djava.net.preferIPv4Stack=true"
      
  lenses:
    image: lensesio/lenses:5.0
    volumes:
      - db_lenses:/var/lenses
    ports:
      - 9991:9991
      - 9102:9102
    environment:
      LENSES_PORT: 9991
      LENSES_SECURITY_USER: admin
      LENSES_SECURITY_PASSWORD: sha256:8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918

volumes:
    db_zookeeper: 
      external: true
    db_kafka: 
      external: true
    db_lenses: 
      external: true
